name: Testing

on:
- push
- pull_request

permissions:
  contents: read

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Setup Go
      id: setup-go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.x'

    - name: Install tools
      run: make install-tools

    - name: Lint
      run: make lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Setup Go
      id: setup-go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.x'

    - name: Test and upload coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: make test-codecov

