name: Testing

on:
- push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
    - name: Setup Go
      id: setup-go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Install tools
      run: make install-tools
    - name: Lint
      run: make lint
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
    - name: Setup Go
      id: setup-go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Test and upload coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: make test-codecov
